import NFTAbi from "./NFTabi.json";
export const abi = NFTAbi.abi;

export const nftData = [
  {
    id: 1,
    name: "Boost on Base #1",
    img: require("../assets/nftAssets/base_01.jpg"),
    price: 0.00001,
  },
  {
    id: 2,
    name: "Boost on Base #2",
    img: require("../assets/nftAssets/base_02.jpg"),
    price: 0.00001,
  },
  {
    id: 3,
    name: "Boost on Base #3",
    img: require("../assets/nftAssets/base_03.jpg"),
    price: 0.00001,
  },
  {
    id: 4,
    name: "Boost on Base #4",
    img: require("../assets/nftAssets/base_04.jpg"),
    price: 0.00001,
  },
  {
    id: 5,
    name: "Boost on Base #5",
    img: require("../assets/nftAssets/base_05.jpg"),
    price: 0.00001,
  },
  {
    id: 6,
    name: "Boost on Base #6",
    img: require("../assets/nftAssets/base_06.jpg"),
    price: 0.00001,
  },
  {
    id: 7,
    name: "Boost on Base #7",
    img: require("../assets/nftAssets/base_07.jpg"),
    price: 0.00001,
  },
  {
    id: 8,
    name: "Boost on Base #8",
    img: require("../assets/nftAssets/base_08.jpg"),
    price: 0.00001,
  },
  {
    id: 9,
    name: "Boost on Base #9",
    img: require("../assets/nftAssets/base_09.jpg"),
    price: 0.00001,
  },
  {
    id: 10,
    name: "Boost on Base #10",
    img: require("../assets/nftAssets/base_10.jpg"),
    price: 0.00001,
  },
  {
    id: 11,
    name: "Boost on Base #11",
    img: require("../assets/nftAssets/base_11.jpg"),
    price: 0.00001,
  },
  {
    id: 12,
    name: "Boost on Base #12",
    img: require("../assets/nftAssets/base_12.jpg"),
    price: 0.00001,
  },
  {
    id: 13,
    name: "Boost on Base #13",
    img: require("../assets/nftAssets/base_13.jpg"),
    price: 0.00001,
  },
  {
    id: 14,
    name: "Boost on Base #14",
    img: require("../assets/nftAssets/base_14.jpg"),
    price: 0.00001,
  },
  {
    id: 15,
    name: "Boost on Base #15",
    img: require("../assets/nftAssets/base_15.jpg"),
    price: 0.00001,
  },
  {
    id: 16,
    name: "Boost on Base #16",
    img: require("../assets/nftAssets/base_16.jpg"),
    price: 0.00001,
  },
  {
    id: 17,
    name: "Boost on Base #17",
    img: require("../assets/nftAssets/base_17.jpg"),
    price: 0.00001,
  },
  {
    id: 18,
    name: "Boost on Base #18",
    img: require("../assets/nftAssets/base_18.jpg"),
    price: 0.00001,
  },
  {
    id: 19,
    name: "Boost on Base #19",
    img: require("../assets/nftAssets/base_19.jpg"),
    price: 0.00001,
  },
  {
    id: 20,
    name: "Boost on Base #20",
    img: require("../assets/nftAssets/base_20.jpg"),
    price: 0.00001,
  },
  {
    id: 21,
    name: "Boost on Base #21",
    img: require("../assets/nftAssets/base_21.jpg"),
    price: 0.00001,
  },
  {
    id: 22,
    name: "Boost on Base #22",
    img: require("../assets/nftAssets/base_22.jpg"),
    price: 0.00001,
  },
  {
    id: 23,
    name: "Boost on Base #23",
    img: require("../assets/nftAssets/base_23.jpg"),
    price: 0.00001,
  },
  {
    id: 24,
    name: "Boost on Base #24",
    img: require("../assets/nftAssets/base_24.jpg"),
    price: 0.00001,
  },
  {
    id: 25,
    name: "Boost on Base #25",
    img: require("../assets/nftAssets/base_25.jpg"),
    price: 0.00001,
  },
  {
    id: 26,
    name: "Boost on Base #26",
    img: require("../assets/nftAssets/base_26.jpg"),
    price: 0.00001,
  },
  {
    id: 27,
    name: "Boost on Base #27",
    img: require("../assets/nftAssets/base_27.jpg"),
    price: 0.00001,
  },
  {
    id: 28,
    name: "Boost on Base #28",
    img: require("../assets/nftAssets/base_28.jpg"),
    price: 0.00001,
  },
  {
    id: 29,
    name: "Boost on Base #29",
    img: require("../assets/nftAssets/base_29.jpg"),
    price: 0.00001,
  },
  {
    id: 30,
    name: "Boost on Base #30",
    img: require("../assets/nftAssets/base_30.jpg"),
    price: 0.00001,
  },
];

export const lineaNFTS = [
  {
    id: 1,
    name: "Boost on Linea #1",
    img: require("../assets/lineaAssets/BOL_01.jpg"),
    price: 0.00001,
  },
  {
    id: 2,
    name: "Boost on Linea #2",
    img: require("../assets/lineaAssets/BOL_02.jpg"),
    price: 0.00001,
  },
  {
    id: 3,
    name: "Boost on Linea #3",
    img: require("../assets/lineaAssets/BOL_03.jpg"),
    price: 0.00001,
  },
  {
    id: 4,
    name: "Boost on Linea #4",
    img: require("../assets/lineaAssets/BOL_04.jpg"),
    price: 0.00001,
  },
  {
    id: 5,
    name: "Boost on Linea #5",
    img: require("../assets/lineaAssets/BOL_05.jpg"),
    price: 0.00001,
  },
  {
    id: 6,
    name: "Boost on Linea #6",
    img: require("../assets/lineaAssets/BOL_06.jpg"),
    price: 0.00001,
  },
  {
    id: 7,
    name: "Boost on Linea #7",
    img: require("../assets/lineaAssets/BOL_07.jpg"),
    price: 0.00001,
  },
  {
    id: 8,
    name: "Boost on Linea #8",
    img: require("../assets/lineaAssets/BOL_08.jpg"),
    price: 0.00001,
  },
  {
    id: 9,
    name: "Boost on Linea #9",
    img: require("../assets/lineaAssets/BOL_09.jpg"),
    price: 0.00001,
  },
  {
    id: 10,
    name: "Boost on Linea #10",
    img: require("../assets/lineaAssets/BOL_10.jpg"),
    price: 0.00001,
  },
  {
    id: 11,
    name: "Boost on Linea #11",
    img: require("../assets/lineaAssets/BOL_11.jpg"),
    price: 0.00001,
  },
  {
    id: 12,
    name: "Boost on Linea #12",
    img: require("../assets/lineaAssets/BOL_12.jpg"),
    price: 0.00001,
  },
  {
    id: 13,
    name: "Boost on Linea #13",
    img: require("../assets/lineaAssets/BOL_13.jpg"),
    price: 0.00001,
  },
  {
    id: 14,
    name: "Boost on Linea #14",
    img: require("../assets/lineaAssets/BOL_14.jpg"),
    price: 0.00001,
  },
  {
    id: 15,
    name: "Boost on Linea #15",
    img: require("../assets/lineaAssets/BOL_15.jpg"),
    price: 0.00001,
  },
  {
    id: 16,
    name: "Boost on Linea #16",
    img: require("../assets/lineaAssets/BOL_16.jpg"),
    price: 0.00001,
  },
  {
    id: 17,
    name: "Boost on Linea #17",
    img: require("../assets/lineaAssets/BOL_17.jpg"),
    price: 0.00001,
  },
  {
    id: 18,
    name: "Boost on Linea #18",
    img: require("../assets/lineaAssets/BOL_18.jpg"),
    price: 0.00001,
  },
  {
    id: 19,
    name: "Boost on Linea #19",
    img: require("../assets/lineaAssets/BOL_19.jpg"),
    price: 0.00001,
  },
  {
    id: 20,
    name: "Boost on Linea #20",
    img: require("../assets/lineaAssets/BOL_20.jpg"),
    price: 0.00001,
  },
  {
    id: 21,
    name: "Boost on Linea #21",
    img: require("../assets/lineaAssets/BOL_21.jpg"),
    price: 0.00001,
  },
  {
    id: 22,
    name: "Boost on Linea #22",
    img: require("../assets/lineaAssets/BOL_22.jpg"),
    price: 0.00001,
  },
  {
    id: 23,
    name: "Boost on Linea #23",
    img: require("../assets/lineaAssets/BOL_23.jpg"),
    price: 0.00001,
  },
  {
    id: 24,
    name: "Boost on Linea #24",
    img: require("../assets/lineaAssets/BOL_24.jpg"),
    price: 0.00001,
  },
  {
    id: 25,
    name: "Boost on Linea #25",
    img: require("../assets/lineaAssets/BOL_25.jpg"),
    price: 0.00001,
  },
  {
    id: 26,
    name: "Boost on Linea #26",
    img: require("../assets/lineaAssets/BOL_26.jpg"),
    price: 0.00001,
  },
  {
    id: 27,
    name: "Boost on Linea #27",
    img: require("../assets/lineaAssets/BOL_27.jpg"),
    price: 0.00001,
  },
  {
    id: 28,
    name: "Boost on Linea #28",
    img: require("../assets/lineaAssets/BOL_28.jpg"),
    price: 0.00001,
  },
  {
    id: 29,
    name: "Boost on Linea #29",
    img: require("../assets/lineaAssets/BOL_29.jpg"),
    price: 0.00001,
  },
  {
    id: 30,
    name: "Boost on Linea #30",
    img: require("../assets/lineaAssets/BOL_30.jpg"),
    price: 0.00001,
  },
];

export const zksyncNFTS = [
  {
    id: 1,
    name: "Boost on ZkSync #1",
    img: require("../assets/zksyncAssets/BOZ_01.jpg"),
    price: 0.00001,
  },
  {
    id: 2,
    name: "Boost on ZkSync #2",
    img: require("../assets/zksyncAssets/BOZ_02.jpg"),
    price: 0.00001,
  },
  {
    id: 3,
    name: "Boost on ZkSync #3",
    img: require("../assets/zksyncAssets/BOZ_03.jpg"),
    price: 0.00001,
  },
  {
    id: 4,
    name: "Boost on ZkSync #4",
    img: require("../assets/zksyncAssets/BOZ_04.jpg"),
    price: 0.00001,
  },
  {
    id: 5,
    name: "Boost on ZkSync #5",
    img: require("../assets/zksyncAssets/BOZ_05.jpg"),
    price: 0.00001,
  },
  {
    id: 6,
    name: "Boost on ZkSync #6",
    img: require("../assets/zksyncAssets/BOZ_06.jpg"),
    price: 0.00001,
  },
  {
    id: 7,
    name: "Boost on ZkSync #7",
    img: require("../assets/zksyncAssets/BOZ_07.jpg"),
    price: 0.00001,
  },
  {
    id: 8,
    name: "Boost on ZkSync #8",
    img: require("../assets/zksyncAssets/BOZ_08.jpg"),
    price: 0.00001,
  },
  {
    id: 9,
    name: "Boost on ZkSync #9",
    img: require("../assets/zksyncAssets/BOZ_09.jpg"),
    price: 0.00001,
  },
  {
    id: 10,
    name: "Boost on ZkSync #10",
    img: require("../assets/zksyncAssets/BOZ_10.jpg"),
    price: 0.00001,
  },
  {
    id: 11,
    name: "Boost on ZkSync #11",
    img: require("../assets/zksyncAssets/BOZ_11.jpg"),
    price: 0.00001,
  },
  {
    id: 12,
    name: "Boost on ZkSync #12",
    img: require("../assets/zksyncAssets/BOZ_12.jpg"),
    price: 0.00001,
  },
  {
    id: 13,
    name: "Boost on ZkSync #13",
    img: require("../assets/zksyncAssets/BOZ_13.jpg"),
    price: 0.00001,
  },
  {
    id: 14,
    name: "Boost on ZkSync #14",
    img: require("../assets/zksyncAssets/BOZ_14.jpg"),
    price: 0.00001,
  },
  {
    id: 15,
    name: "Boost on ZkSync #15",
    img: require("../assets/zksyncAssets/BOZ_15.jpg"),
    price: 0.00001,
  },
  {
    id: 16,
    name: "Boost on ZkSync #16",
    img: require("../assets/zksyncAssets/BOZ_16.jpg"),
    price: 0.00001,
  },
  {
    id: 17,
    name: "Boost on ZkSync #17",
    img: require("../assets/zksyncAssets/BOZ_17.jpg"),
    price: 0.00001,
  },
  {
    id: 18,
    name: "Boost on ZkSync #18",
    img: require("../assets/zksyncAssets/BOZ_18.jpg"),
    price: 0.00001,
  },
  {
    id: 19,
    name: "Boost on ZkSync #19",
    img: require("../assets/zksyncAssets/BOZ_19.jpg"),
    price: 0.00001,
  },
  {
    id: 20,
    name: "Boost on ZkSync #20",
    img: require("../assets/zksyncAssets/BOZ_20.jpg"),
    price: 0.00001,
  },
  {
    id: 21,
    name: "Boost on ZkSync #21",
    img: require("../assets/zksyncAssets/BOZ_21.jpg"),
    price: 0.00001,
  },
  {
    id: 22,
    name: "Boost on ZkSync #22",
    img: require("../assets/zksyncAssets/BOZ_22.jpg"),
    price: 0.00001,
  },
  {
    id: 23,
    name: "Boost on ZkSync #23",
    img: require("../assets/zksyncAssets/BOZ_23.jpg"),
    price: 0.00001,
  },
  {
    id: 24,
    name: "Boost on ZkSync #24",
    img: require("../assets/zksyncAssets/BOZ_24.jpg"),
    price: 0.00001,
  },
  {
    id: 25,
    name: "Boost on ZkSync #25",
    img: require("../assets/zksyncAssets/BOZ_25.jpg"),
    price: 0.00001,
  },
  {
    id: 26,
    name: "Boost on ZkSync #26",
    img: require("../assets/zksyncAssets/BOZ_26.jpg"),
    price: 0.00001,
  },
  {
    id: 27,
    name: "Boost on ZkSync #27",
    img: require("../assets/zksyncAssets/BOZ_27.jpg"),
    price: 0.00001,
  },
  {
    id: 28,
    name: "Boost on ZkSync #28",
    img: require("../assets/zksyncAssets/BOZ_28.jpg"),
    price: 0.00001,
  },
  {
    id: 29,
    name: "Boost on ZkSync #29",
    img: require("../assets/zksyncAssets/BOZ_29.jpg"),
    price: 0.00001,
  },
  {
    id: 30,
    name: "Boost on ZkSync #30",
    img: require("../assets/zksyncAssets/BOZ_30.jpg"),
    price: 0.00001,
  },
];
