export const nftData = [
  {
    id: 1,
    name: "Boost on Base #1",
    img: require("../assets/nftAssets/base_01.jpg"),
    price: 0.00001,
  },
  {
    id: 2,
    name: "Boost on Base #2",
    img: require("../assets/nftAssets/base_02.jpg"),
    price: 0.00001,
  },
  {
    id: 3,
    name: "Boost on Base #3",
    img: require("../assets/nftAssets/base_03.jpg"),
    price: 0.00001,
  },
  {
    id: 4,
    name: "Boost on Base #4",
    img: require("../assets/nftAssets/base_04.jpg"),
    price: 0.00001,
  },
  {
    id: 5,
    name: "Boost on Base #5",
    img: require("../assets/nftAssets/base_05.jpg"),
    price: 0.00001,
  },
  {
    id: 6,
    name: "Boost on Base #6",
    img: require("../assets/nftAssets/base_06.jpg"),
    price: 0.00001,
  },
  {
    id: 7,
    name: "Boost on Base #7",
    img: require("../assets/nftAssets/base_07.jpg"),
    price: 0.00001,
  },
  {
    id: 8,
    name: "Boost on Base #8",
    img: require("../assets/nftAssets/base_08.jpg"),
    price: 0.00001,
  },
  {
    id: 9,
    name: "Boost on Base #9",
    img: require("../assets/nftAssets/base_09.jpg"),
    price: 0.00001,
  },
  {
    id: 10,
    name: "Boost on Base #10",
    img: require("../assets/nftAssets/base_10.jpg"),
    price: 0.00001,
  },
  {
    id: 11,
    name: "Boost on Base #11",
    img: require("../assets/nftAssets/base_11.jpg"),
    price: 0.00001,
  },
  {
    id: 12,
    name: "Boost on Base #12",
    img: require("../assets/nftAssets/base_12.jpg"),
    price: 0.00001,
  },
  {
    id: 13,
    name: "Boost on Base #13",
    img: require("../assets/nftAssets/base_13.jpg"),
    price: 0.00001,
  },
  {
    id: 14,
    name: "Boost on Base #14",
    img: require("../assets/nftAssets/base_14.jpg"),
    price: 0.00001,
  },
  {
    id: 15,
    name: "Boost on Base #15",
    img: require("../assets/nftAssets/base_15.jpg"),
    price: 0.00001,
  },
  {
    id: 16,
    name: "Boost on Base #16",
    img: require("../assets/nftAssets/base_16.jpg"),
    price: 0.00001,
  },
  {
    id: 17,
    name: "Boost on Base #17",
    img: require("../assets/nftAssets/base_17.jpg"),
    price: 0.00001,
  },
  {
    id: 18,
    name: "Boost on Base #18",
    img: require("../assets/nftAssets/base_18.jpg"),
    price: 0.00001,
  },
  {
    id: 19,
    name: "Boost on Base #19",
    img: require("../assets/nftAssets/base_19.jpg"),
    price: 0.00001,
  },
  {
    id: 20,
    name: "Boost on Base #20",
    img: require("../assets/nftAssets/base_20.jpg"),
    price: 0.00001,
  },
  {
    id: 21,
    name: "Boost on Base #21",
    img: require("../assets/nftAssets/base_21.jpg"),
    price: 0.00001,
  },
  {
    id: 22,
    name: "Boost on Base #22",
    img: require("../assets/nftAssets/base_22.jpg"),
    price: 0.00001,
  },
  {
    id: 23,
    name: "Boost on Base #23",
    img: require("../assets/nftAssets/base_23.jpg"),
    price: 0.00001,
  },
  {
    id: 24,
    name: "Boost on Base #24",
    img: require("../assets/nftAssets/base_24.jpg"),
    price: 0.00001,
  },
  {
    id: 25,
    name: "Boost on Base #25",
    img: require("../assets/nftAssets/base_25.jpg"),
    price: 0.00001,
  },
  {
    id: 26,
    name: "Boost on Base #26",
    img: require("../assets/nftAssets/base_26.jpg"),
    price: 0.00001,
  },
  {
    id: 27,
    name: "Boost on Base #27",
    img: require("../assets/nftAssets/base_27.jpg"),
    price: 0.00001,
  },
  {
    id: 28,
    name: "Boost on Base #28",
    img: require("../assets/nftAssets/base_28.jpg"),
    price: 0.00001,
  },
  {
    id: 29,
    name: "Boost on Base #29",
    img: require("../assets/nftAssets/base_29.jpg"),
    price: 0.00001,
  },
  {
    id: 30,
    name: "Boost on Base #30",
    img: require("../assets/nftAssets/base_30.jpg"),
    price: 0.00001,
  },
];
